### ISSUE TITLE
OSSDC-SIM  launch issue

### ISSUE THREAD

**Issue by Sam827-r** [OSSDC/OSSDC-SIM#12]
I have working on ubuntu 18.04 ,since i followed up all instruction to and able  launch sim but unfortunately sim get hang up after launch. no option are working like link to cloud or python api is not visible,but after clicking on Visual Editor API ready message displyed.somewhat weird behavior for OSSDC-SIM on Ubuntu machines.
![Screenshot from 2022-12-05 14-17-26](https://user-images.githubusercontent.com/107983720/205593495-ded77ae4-ebe6-4311-9cd1-9faf279c98b9.png)

**Comment by filipthoen2** [comment]
How did you start the simulator?

See issue " can't start the simulator #7 " which explains the exact command line. I had to start it the suggested way or I would observe the same issue was you.

**Comment by ShoukatM** [comment]
Hi @filipthoen2 ,

thanks for response  .
 I have resolved my issue after cloning multiple times, it seems to be some  packages issue

**Comment by ShoukatM** [comment]
Hi @Sam827-r , 
I have resolved issue. After cloning sim multiple times might be some Ubuntu package issue.
